# Generated by Django 5.1.15 on 2026-09-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('password', models.CharField(db_column='mat_khau', max_length=128)),
                ('ho_ten', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Địa chỉ Email')),
                ('so_dien_thoai', models.CharField(max_length=10, unique=True, verbose_name='Số điện thoại')),
                ('vai_tro', models.CharField(choices=[('KHACH_THUE', 'Khách thuê'), ('CHU_NHA', 'Chủ nhà'), ('QUAN_LY', 'Quản lý tòa nhà'), ('ADMIN', 'Quản trị hệ thống')], default='KHACH_THUE', max_length=20, verbose_name='Vai trò')),
                ('is_active', models.BooleanField(db_column='dang_hoat_dong', default=True, verbose_name='Đang hoạt động')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Nhân viên hệ thống')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Tài khoản',
                'verbose_name_plural': 'Danh sách tài khoản',
                'db_table': 'tai_khoan',
                'indexes': [models.Index(fields=['vai_tro', 'is_active'], name='idx_tk_vaitro_hoatdong')],
            },
        ),
    ]
