# Generated by Django 5.1.15 on 2026-09-25 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThuHoiAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(db_index=True, max_length=64, unique=True)),
                ('ngay_het_han', models.DateTimeField()),
                ('ngay_thu_hoi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Access Token bị thu hồi',
                'verbose_name_plural': 'Danh sách Access Token bị thu hồi',
                'db_table': 'thu_hoi_access_token',
            },
        ),
        migrations.AddField(
            model_name='taikhoan',
            name='khoa_den',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Khóa đăng nhập đến'),
        ),
        migrations.AddField(
            model_name='taikhoan',
            name='lan_sai_cuoi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm sai gần nhất'),
        ),
        migrations.AddField(
            model_name='taikhoan',
            name='so_lan_sai',
            field=models.IntegerField(default=0, verbose_name='Số lần đăng nhập sai'),
        ),
        migrations.AddField(
            model_name='taikhoan',
            name='thoi_diem_dang_xuat',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm đăng xuất gần nhất'),
        ),
        migrations.CreateModel(
            name='PhienDangNhap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_het_han', models.DateTimeField()),
                ('da_thu_hoi', models.BooleanField(default=False)),
                ('tai_khoan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phien_dang_nhap', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phiên đăng nhập',
                'verbose_name_plural': 'Danh sách phiên đăng nhập',
                'db_table': 'phien_dang_nhap',
            },
        ),
    ]
