# Generated by Django 5.1.15 on 2026-09-25 16:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_thuhoiaccesstoken_taikhoan_khoa_den_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KhachThue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ho_ten", models.CharField(max_length=100, verbose_name="Họ tên")),
                ("ngay_sinh", models.DateField(verbose_name="Ngày sinh")),
                (
                    "so_giay_to",
                    models.CharField(
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Số căn cước chỉ được gồm 9 hoặc 12 chữ số.",
                                regex="\\A(?:[0-9]{9}|[0-9]{12})\\Z",
                            )
                        ],
                        verbose_name="Số căn cước",
                    ),
                ),
                ("que_quan", models.CharField(max_length=255, verbose_name="Quê quán")),
                (
                    "nghe_nghiep",
                    models.CharField(max_length=150, verbose_name="Nghề nghiệp"),
                ),
                ("ngay_tao", models.DateTimeField(auto_now_add=True)),
                (
                    "tai_khoan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ho_so_khach_thue",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hồ sơ khách thuê",
                "verbose_name_plural": "Hồ sơ khách thuê",
                "db_table": "khach_thue",
            },
        ),
    ]
