# Generated by Django 5.1.15 on 2026-09-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_khachthue"),
    ]

    operations = [
        migrations.AddField(
            model_name="khachthue",
            name="anh_giay_to_sau",
            field=models.FileField(
                blank=True,
                max_length=255,
                upload_to="giay-to/",
                verbose_name="Ảnh mặt sau",
            ),
        ),
        migrations.AddField(
            model_name="khachthue",
            name="anh_giay_to_truoc",
            field=models.FileField(
                blank=True,
                max_length=255,
                upload_to="giay-to/",
                verbose_name="Ảnh mặt trước",
            ),
        ),
    ]
