# Generated by Django 5.1.15 on 2026-09-25 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_khachthue_anh_giay_to_sau_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhongTro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ma_phong", models.CharField(max_length=20, verbose_name="Mã phòng")),
            ],
            options={
                "verbose_name": "Phòng trọ",
                "verbose_name_plural": "Phòng trọ",
                "db_table": "phong_tro",
            },
        ),
        migrations.CreateModel(
            name="HopDong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ma_hop_dong",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Mã hợp đồng"
                    ),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("NHAP", "Nháp"),
                            ("CHO_HIEU_LUC", "Chờ hiệu lực"),
                            ("DANG_HIEU_LUC", "Đang hiệu lực"),
                            ("DA_KET_THUC", "Đã kết thúc"),
                            ("DA_HUY", "Đã hủy"),
                        ],
                        default="NHAP",
                        max_length=25,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "ngay_tra_phong",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày trả phòng"
                    ),
                ),
                (
                    "khach_dung_ten",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.khachthue",
                    ),
                ),
                (
                    "phong",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.phongtro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hợp đồng",
                "verbose_name_plural": "Hợp đồng",
                "db_table": "hop_dong",
            },
        ),
        migrations.CreateModel(
            name="ToaNha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_toa_nha",
                    models.CharField(max_length=150, verbose_name="Tên tòa nhà"),
                ),
                (
                    "chu_nha",
                    models.ForeignKey(
                        limit_choices_to={"vai_tro": "CHU_NHA"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tòa nhà",
                "verbose_name_plural": "Tòa nhà",
                "db_table": "toa_nha",
            },
        ),
        migrations.AddField(
            model_name="phongtro",
            name="toa_nha",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="accounts.toanha"
            ),
        ),
        migrations.CreateModel(
            name="KyHopDong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "so_thu_tu",
                    models.PositiveIntegerField(default=1, verbose_name="Số thứ tự"),
                ),
                ("ngay_bat_dau", models.DateField(verbose_name="Ngày bắt đầu")),
                ("ngay_ket_thuc", models.DateField(verbose_name="Ngày kết thúc")),
                (
                    "hop_dong",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cac_ky",
                        to="accounts.hopdong",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kỳ hợp đồng",
                "verbose_name_plural": "Kỳ hợp đồng",
                "db_table": "ky_hop_dong",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("hop_dong", "so_thu_tu"), name="unique_so_ky_hop_dong"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("ngay_ket_thuc__gte", models.F("ngay_bat_dau"))
                        ),
                        name="ky_hop_dong_ngay_hop_le",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("so_thu_tu__gte", 1)),
                        name="ky_hop_dong_thu_tu_duong",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="phongtro",
            constraint=models.UniqueConstraint(
                fields=("toa_nha", "ma_phong"), name="unique_phong_trong_toa"
            ),
        ),
    ]
